package com.shark.weipan.dto;

public class TestMybatis {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_mybatis.id
     *
     * @mbggenerated Mon Sep 12 21:28:28 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_mybatis.name
     *
     * @mbggenerated Mon Sep 12 21:28:28 CST 2016
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_mybatis.id
     *
     * @return the value of test_mybatis.id
     *
     * @mbggenerated Mon Sep 12 21:28:28 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_mybatis.id
     *
     * @param id the value for test_mybatis.id
     *
     * @mbggenerated Mon Sep 12 21:28:28 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_mybatis.name
     *
     * @return the value of test_mybatis.name
     *
     * @mbggenerated Mon Sep 12 21:28:28 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_mybatis.name
     *
     * @param name the value for test_mybatis.name
     *
     * @mbggenerated Mon Sep 12 21:28:28 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }
}