package com.shark.mvctemp.dto;

import java.util.ArrayList;
import java.util.List;

public class ProjectExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project
     *
     * @mbggenerated Wed Sep 07 08:23:30 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project
     *
     * @mbggenerated Wed Sep 07 08:23:30 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project
     *
     * @mbggenerated Wed Sep 07 08:23:30 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Wed Sep 07 08:23:30 CST 2016
     */
    public ProjectExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Wed Sep 07 08:23:30 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Wed Sep 07 08:23:30 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Wed Sep 07 08:23:30 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Wed Sep 07 08:23:30 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Wed Sep 07 08:23:30 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Wed Sep 07 08:23:30 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Wed Sep 07 08:23:30 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Wed Sep 07 08:23:30 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Wed Sep 07 08:23:30 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Wed Sep 07 08:23:30 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project
     *
     * @mbggenerated Wed Sep 07 08:23:30 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(Integer value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(Integer value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(Integer value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(Integer value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(Integer value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<Integer> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<Integer> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(Integer value1, Integer value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(Integer value1, Integer value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectValueIsNull() {
            addCriterion("project_value is null");
            return (Criteria) this;
        }

        public Criteria andProjectValueIsNotNull() {
            addCriterion("project_value is not null");
            return (Criteria) this;
        }

        public Criteria andProjectValueEqualTo(String value) {
            addCriterion("project_value =", value, "projectValue");
            return (Criteria) this;
        }

        public Criteria andProjectValueNotEqualTo(String value) {
            addCriterion("project_value <>", value, "projectValue");
            return (Criteria) this;
        }

        public Criteria andProjectValueGreaterThan(String value) {
            addCriterion("project_value >", value, "projectValue");
            return (Criteria) this;
        }

        public Criteria andProjectValueGreaterThanOrEqualTo(String value) {
            addCriterion("project_value >=", value, "projectValue");
            return (Criteria) this;
        }

        public Criteria andProjectValueLessThan(String value) {
            addCriterion("project_value <", value, "projectValue");
            return (Criteria) this;
        }

        public Criteria andProjectValueLessThanOrEqualTo(String value) {
            addCriterion("project_value <=", value, "projectValue");
            return (Criteria) this;
        }

        public Criteria andProjectValueLike(String value) {
            addCriterion("project_value like", value, "projectValue");
            return (Criteria) this;
        }

        public Criteria andProjectValueNotLike(String value) {
            addCriterion("project_value not like", value, "projectValue");
            return (Criteria) this;
        }

        public Criteria andProjectValueIn(List<String> values) {
            addCriterion("project_value in", values, "projectValue");
            return (Criteria) this;
        }

        public Criteria andProjectValueNotIn(List<String> values) {
            addCriterion("project_value not in", values, "projectValue");
            return (Criteria) this;
        }

        public Criteria andProjectValueBetween(String value1, String value2) {
            addCriterion("project_value between", value1, value2, "projectValue");
            return (Criteria) this;
        }

        public Criteria andProjectValueNotBetween(String value1, String value2) {
            addCriterion("project_value not between", value1, value2, "projectValue");
            return (Criteria) this;
        }

        public Criteria andProjdectNameIsNull() {
            addCriterion("projdect_name is null");
            return (Criteria) this;
        }

        public Criteria andProjdectNameIsNotNull() {
            addCriterion("projdect_name is not null");
            return (Criteria) this;
        }

        public Criteria andProjdectNameEqualTo(String value) {
            addCriterion("projdect_name =", value, "projdectName");
            return (Criteria) this;
        }

        public Criteria andProjdectNameNotEqualTo(String value) {
            addCriterion("projdect_name <>", value, "projdectName");
            return (Criteria) this;
        }

        public Criteria andProjdectNameGreaterThan(String value) {
            addCriterion("projdect_name >", value, "projdectName");
            return (Criteria) this;
        }

        public Criteria andProjdectNameGreaterThanOrEqualTo(String value) {
            addCriterion("projdect_name >=", value, "projdectName");
            return (Criteria) this;
        }

        public Criteria andProjdectNameLessThan(String value) {
            addCriterion("projdect_name <", value, "projdectName");
            return (Criteria) this;
        }

        public Criteria andProjdectNameLessThanOrEqualTo(String value) {
            addCriterion("projdect_name <=", value, "projdectName");
            return (Criteria) this;
        }

        public Criteria andProjdectNameLike(String value) {
            addCriterion("projdect_name like", value, "projdectName");
            return (Criteria) this;
        }

        public Criteria andProjdectNameNotLike(String value) {
            addCriterion("projdect_name not like", value, "projdectName");
            return (Criteria) this;
        }

        public Criteria andProjdectNameIn(List<String> values) {
            addCriterion("projdect_name in", values, "projdectName");
            return (Criteria) this;
        }

        public Criteria andProjdectNameNotIn(List<String> values) {
            addCriterion("projdect_name not in", values, "projdectName");
            return (Criteria) this;
        }

        public Criteria andProjdectNameBetween(String value1, String value2) {
            addCriterion("projdect_name between", value1, value2, "projdectName");
            return (Criteria) this;
        }

        public Criteria andProjdectNameNotBetween(String value1, String value2) {
            addCriterion("projdect_name not between", value1, value2, "projdectName");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Boolean value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Boolean value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Boolean value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Boolean value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Boolean> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Boolean> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project
     *
     * @mbggenerated do_not_delete_during_merge Wed Sep 07 08:23:30 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project
     *
     * @mbggenerated Wed Sep 07 08:23:30 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}