package com.shark.mvctemp.dto;

public class Project {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_id
     *
     * @mbggenerated Wed Sep 07 08:23:30 CST 2016
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_value
     *
     * @mbggenerated Wed Sep 07 08:23:30 CST 2016
     */
    private String projectValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.projdect_name
     *
     * @mbggenerated Wed Sep 07 08:23:30 CST 2016
     */
    private String projdectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.status
     *
     * @mbggenerated Wed Sep 07 08:23:30 CST 2016
     */
    private Boolean status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_id
     *
     * @return the value of project.project_id
     *
     * @mbggenerated Wed Sep 07 08:23:30 CST 2016
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_id
     *
     * @param projectId the value for project.project_id
     *
     * @mbggenerated Wed Sep 07 08:23:30 CST 2016
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_value
     *
     * @return the value of project.project_value
     *
     * @mbggenerated Wed Sep 07 08:23:30 CST 2016
     */
    public String getProjectValue() {
        return projectValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_value
     *
     * @param projectValue the value for project.project_value
     *
     * @mbggenerated Wed Sep 07 08:23:30 CST 2016
     */
    public void setProjectValue(String projectValue) {
        this.projectValue = projectValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.projdect_name
     *
     * @return the value of project.projdect_name
     *
     * @mbggenerated Wed Sep 07 08:23:30 CST 2016
     */
    public String getProjdectName() {
        return projdectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.projdect_name
     *
     * @param projdectName the value for project.projdect_name
     *
     * @mbggenerated Wed Sep 07 08:23:30 CST 2016
     */
    public void setProjdectName(String projdectName) {
        this.projdectName = projdectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.status
     *
     * @return the value of project.status
     *
     * @mbggenerated Wed Sep 07 08:23:30 CST 2016
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.status
     *
     * @param status the value for project.status
     *
     * @mbggenerated Wed Sep 07 08:23:30 CST 2016
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}